version: "3"

services:
  # elastic:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"

  jaeger-all-in-one:
    image: jaegertracing/all-in-one
    # environment:
    #   - SPAN_STORAGE_TYPE=elasticsearch
    #   - ES_SERVER_URLS=http://elastic:9200
    ports:
      - 16686:16686 # serve frontend
      - 14268:14268
      - 14250:14250 # collector
    deploy:
      restart_policy: # bad workaround, just to simplify the demo.
        condition: on-failure
    # depends_on:
    #   - elastic

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"

  # zipkin-all-in-one:
  #   image: openzipkin/zipkin:latest
  #   restart: always
  #   ports:
  #     - "9411:9411"

  # prometheus:
  #   image: prom/prometheus
  #   volumes:
  #     - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - 9090:9090

  collector-gateway:
    image: otel/opentelemetry-collector:0.29.0
    volumes:
      - ./config/collector-gateway.yml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "9464:9464"
      - "4317:4317" # OTLP GRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
